'use strict';
import unfold from './lib/unfold.js';

const numbers = Array.from(new Array(100).keys()).map(i => ++i);// 1..100の連番の配列生成
const result = numbers                               // 配列を...
  .filter(number => number % 3 !== 0)                // 何かの条件で絞って...
  .map(number => number * 2)                         // 加工して...
  .filter(number => number <= 100)                   // さらに絞って...
  .reduce((sum, number) => sum + number);            // 合計していると。
console.log(result);// 1734